// Generated from https://github.com/typst/codex/blob/main/src/modules/sym.txt

import { Error, Ok, toList } from "../../gleam.mjs";

export function grapheme_to_notations(grapheme) {
  let notations = map_grapheme_to_notations.get(grapheme);
  if (notations === undefined) {
    return new toList([]);
  } else {
    return new toList(notations);
  }
}

export function notation_to_grapheme(notation) {
  let grapheme = map_notation_to_grapheme.get(notation);
  if (grapheme === undefined) {
    return new Error(undefined);
  } else {
    return new Ok(grapheme);
  }
}

const notation_table = [
["\u{0020}", "space"],
["\u{0021}", "excl"],
["\u{0022}", "quote.double"],
["\u{0023}\u{FE0E}", "hash"],
["\u{0024}", "dollar", "pataca", "peso"],
["\u{0025}", "percent"],
["\u{0026}", "amp"],
["\u{0027}", "quote.single"],
["\u{0028}", "paren.l"],
["\u{0029}", "paren.r"],
["\u{002A}\u{FE0E}", "ast.basic"],
["\u{002B}", "plus"],
["\u{002C}", "comma"],
["\u{002D}", "hyph.minus"],
["\u{002E}", "dot.basic"],
["\u{002F}", "slash"],
["\u{003A}", "colon"],
["\u{003B}", "semi"],
["\u{003C}", "lt"],
["\u{003D}", "eq"],
["\u{003E}", "gt"],
["\u{003F}", "quest"],
["\u{005B}", "bracket.l"],
["\u{005C}", "backslash"],
["\u{005D}", "bracket.r"],
["\u{005E}", "hat"],
["\u{0060}", "grave"],
["\u{007B}", "brace.l"],
["\u{007C}", "bar.v"],
["\u{007D}", "brace.r"],
["\u{007E}", "tilde.basic"],
["\u{00A0}", "space.nobreak"],
["\u{00A1}", "excl.inv"],
["\u{00A2}", "cent"],
["\u{00A3}", "pound"],
["\u{00A4}", "currency"],
["\u{00A5}", "yen", "yuan"],
["\u{00A6}", "bar.v.broken"],
["\u{00A7}", "section"],
["\u{00A8}", "diaer", "dot.double"],
["\u{00A9}\u{FE0E}", "copyright"],
["\u{00AB}", "quote.angle.l.double", "quote.chevron.l.double"],
["\u{00AC}", "not"],
["\u{00AD}", "hyph.soft"],
["\u{00AE}\u{FE0E}", "trademark.registered"],
["\u{00AF}", "macron"],
["\u{00B0}", "degree"],
["\u{00B1}", "plus.minus"],
["\u{00B4}", "acute"],
["\u{00B6}", "pilcrow"],
["\u{00B7}", "dot.c"],
["\u{00BB}", "quote.angle.r.double", "quote.chevron.r.double"],
["\u{00BF}", "quest.inv"],
["\u{00C5}", "angstrom"],
["\u{00D7}", "times"],
["\u{00F7}", "div"],
["\u{0127}", "planck", "planck.reduce"],
["\u{0131}", "dotless.i"],
["\u{0237}", "dotless.j"],
["\u{02C7}", "caron"],
["\u{02D8}", "breve"],
["\u{02DD}", "acute.double"],
["\u{0391}", "Alpha"],
["\u{0392}", "Beta"],
["\u{0393}", "Gamma"],
["\u{0394}", "Delta"],
["\u{0395}", "Epsilon"],
["\u{0396}", "Zeta"],
["\u{0397}", "Eta"],
["\u{0398}", "Theta"],
["\u{0399}", "Iota"],
["\u{039A}", "Kappa"],
["\u{039B}", "Lambda"],
["\u{039C}", "Mu"],
["\u{039D}", "Nu"],
["\u{039E}", "Xi"],
["\u{039F}", "Omicron"],
["\u{03A0}", "Pi"],
["\u{03A1}", "Rho"],
["\u{03A3}", "Sigma"],
["\u{03A4}", "Tau"],
["\u{03A5}", "Upsilon"],
["\u{03A6}", "Phi"],
["\u{03A7}", "Chi"],
["\u{03A8}", "Psi"],
["\u{03A9}", "Omega"],
["\u{03B1}", "alpha"],
["\u{03B2}", "beta"],
["\u{03B3}", "gamma"],
["\u{03B4}", "delta"],
["\u{03B5}", "epsilon"],
["\u{03B6}", "zeta"],
["\u{03B7}", "eta"],
["\u{03B8}", "theta"],
["\u{03B9}", "iota"],
["\u{03BA}", "kappa"],
["\u{03BB}", "lambda"],
["\u{03BC}", "mu"],
["\u{03BD}", "nu"],
["\u{03BE}", "xi"],
["\u{03BF}", "omicron"],
["\u{03C0}", "pi"],
["\u{03C1}", "rho"],
["\u{03C2}", "sigma.alt"],
["\u{03C3}", "sigma"],
["\u{03C4}", "tau"],
["\u{03C5}", "upsilon"],
["\u{03C6}", "phi"],
["\u{03C7}", "chi"],
["\u{03C8}", "psi"],
["\u{03C9}", "omega"],
["\u{03CF}", "Kai"],
["\u{03D0}", "beta.alt"],
["\u{03D1}", "theta.alt"],
["\u{03D5}", "phi.alt"],
["\u{03D6}", "pi.alt"],
["\u{03D7}", "kai"],
["\u{03DC}", "Digamma"],
["\u{03DD}", "digamma"],
["\u{03F0}", "kappa.alt"],
["\u{03F1}", "rho.alt"],
["\u{03F4}", "Theta.alt"],
["\u{03F5}", "epsilon.alt"],
["\u{03F6}", "epsilon.alt.rev"],
["\u{0428}", "Sha"],
["\u{0448}", "sha"],
["\u{058F}", "dram"],
["\u{05D0}", "alef", "aleph"],
["\u{05D1}", "bet", "beth"],
["\u{05D2}", "gimel", "gimmel"],
["\u{05D3}", "dalet", "daleth"],
["\u{05E9}", "shin"],
["\u{060B}", "afghani"],
["\u{07FE}", "dorome"],
["\u{07FF}", "taman"],
["\u{09F3}", "taka"],
["\u{0BF9}", "rupee.tamil"],
["\u{0E3F}", "baht"],
["\u{17DB}", "riel"],
["\u{2002}", "space.en"],
["\u{2003}", "space.quad"],
["\u{2004}", "space.third"],
["\u{2005}", "space.quarter"],
["\u{2006}", "space.sixth"],
["\u{2007}", "space.fig"],
["\u{2008}", "space.punct"],
["\u{2009}", "space.thin"],
["\u{200A}", "space.hair"],
["\u{200B}", "zws"],
["\u{200C}", "zwnj"],
["\u{200D}", "zwj"],
["\u{200E}", "lrm"],
["\u{200F}", "rlm"],
["\u{2010}", "hyph"],
["\u{2011}", "hyph.nobreak"],
["\u{2012}", "dash.fig"],
["\u{2013}", "dash.en"],
["\u{2014}", "dash.em"],
["\u{2015}", "bar.h"],
["\u{2016}", "bar.v.double"],
["\u{2018}", "quote.l.single"],
["\u{2019}", "quote.r.single"],
["\u{201A}", "quote.low.single"],
["\u{201B}", "quote.high.single"],
["\u{201C}", "quote.l.double"],
["\u{201D}", "quote.r.double"],
["\u{201E}", "quote.low.double"],
["\u{201F}", "quote.high.double"],
["\u{2020}", "dagger"],
["\u{2021}", "dagger.double"],
["\u{2022}", "bullet"],
["\u{2023}", "bullet.tri"],
["\u{2026}", "dots.h"],
["\u{2027}", "hyph.point"],
["\u{202F}", "space.nobreak.narrow"],
["\u{2030}", "permille"],
["\u{2031}", "permyriad"],
["\u{2032}", "prime"],
["\u{2033}", "prime.double"],
["\u{2034}", "prime.triple"],
["\u{2035}", "prime.rev"],
["\u{2036}", "prime.double.rev"],
["\u{2037}", "prime.triple.rev"],
["\u{2038}", "caret"],
["\u{2039}", "quote.angle.l.single", "quote.chevron.l.single"],
["\u{203A}", "quote.angle.r.single", "quote.chevron.r.single"],
["\u{203B}", "refmark"],
["\u{203C}\u{FE0E}", "excl.double"],
["\u{203D}", "interrobang"],
["\u{2042}", "ast.triple"],
["\u{2043}", "bullet.hyph"],
["\u{2047}", "quest.double"],
["\u{2048}", "quest.excl"],
["\u{2049}\u{FE0E}", "excl.quest"],
["\u{204B}", "pilcrow.rev"],
["\u{204C}", "bullet.l"],
["\u{204D}", "bullet.r"],
["\u{204E}", "ast.low"],
["\u{204F}", "semi.rev"],
["\u{2051}", "ast.double"],
["\u{2057}", "prime.quad"],
["\u{205D}", "colon.tri"],
["\u{205F}", "space.med"],
["\u{2060}", "wj"],
["\u{20A1}", "colon.currency"],
["\u{20A3}", "franc"],
["\u{20A6}", "naira"],
["\u{20A8}", "rupee.generic"],
["\u{20A9}", "won"],
["\u{20AA}", "shekel"],
["\u{20AB}", "dong"],
["\u{20AC}", "euro"],
["\u{20AD}", "kip"],
["\u{20AE}", "togrog"],
["\u{20B1}", "peso.philippine"],
["\u{20B2}", "guarani"],
["\u{20B4}", "hryvnia"],
["\u{20B5}", "cedi"],
["\u{20B8}", "tenge"],
["\u{20B9}", "rupee.indian"],
["\u{20BA}", "lira"],
["\u{20BC}", "manat"],
["\u{20BD}", "ruble"],
["\u{20BE}", "lari"],
["\u{20BF}", "bitcoin"],
["\u{20C0}", "som"],
["\u{20DB}", "dot.triple"],
["\u{20DC}", "dot.quad"],
["\u{2102}", "CC"],
["\u{2105}", "co"],
["\u{210D}", "HH"],
["\u{2111}", "Im"],
["\u{2113}", "ell"],
["\u{2115}", "NN"],
["\u{2116}", "numero"],
["\u{2117}", "copyright.sound"],
["\u{2119}", "PP"],
["\u{211A}", "QQ"],
["\u{211C}", "Re"],
["\u{211D}", "RR"],
["\u{2120}", "trademark.service"],
["\u{2122}\u{FE0E}", "trademark"],
["\u{2124}", "ZZ"],
["\u{2127}", "Omega.inv"],
["\u{2129}", "iota.inv"],
["\u{214B}", "amp.inv"],
["\u{2190}", "arrow.l"],
["\u{2191}", "arrow.t"],
["\u{2192}", "arrow.r"],
["\u{2193}", "arrow.b"],
["\u{2194}\u{FE0E}", "arrow.l.r"],
["\u{2195}\u{FE0E}", "arrow.t.b"],
["\u{2196}\u{FE0E}", "arrow.tl"],
["\u{2197}\u{FE0E}", "arrow.tr"],
["\u{2198}\u{FE0E}", "arrow.br"],
["\u{2199}\u{FE0E}", "arrow.bl"],
["\u{219A}", "arrow.l.not"],
["\u{219B}", "arrow.r.not"],
["\u{219C}", "arrow.l.wave"],
["\u{219D}", "arrow.r.wave"],
["\u{219E}", "arrow.l.twohead"],
["\u{219F}", "arrow.t.twohead"],
["\u{21A0}", "arrow.r.twohead"],
["\u{21A1}", "arrow.b.twohead"],
["\u{21A2}", "arrow.l.tail"],
["\u{21A3}", "arrow.r.tail"],
["\u{21A4}", "arrow.l.bar"],
["\u{21A5}", "arrow.t.bar"],
["\u{21A6}", "arrow.r.bar", "mapsto"],
["\u{21A7}", "arrow.b.bar"],
["\u{21A9}\u{FE0E}", "arrow.l.hook"],
["\u{21AA}\u{FE0E}", "arrow.r.hook"],
["\u{21AB}", "arrow.l.loop"],
["\u{21AC}", "arrow.r.loop"],
["\u{21AD}", "arrow.l.r.wave"],
["\u{21AE}", "arrow.l.r.not"],
["\u{21AF}", "arrow.zigzag"],
["\u{21B6}", "arrow.ccw.half"],
["\u{21B7}", "arrow.cw.half"],
["\u{21B9}", "arrows.lr.stop"],
["\u{21BA}", "arrow.ccw"],
["\u{21BB}", "arrow.cw"],
["\u{21BC}", "harpoon.lt"],
["\u{21BD}", "harpoon.lb"],
["\u{21BE}", "harpoon.tr"],
["\u{21BF}", "harpoon.tl"],
["\u{21C0}", "harpoon.rt"],
["\u{21C1}", "harpoon.rb"],
["\u{21C2}", "harpoon.br"],
["\u{21C3}", "harpoon.bl"],
["\u{21C4}", "arrows.rl"],
["\u{21C5}", "arrows.tb"],
["\u{21C6}", "arrows.lr"],
["\u{21C7}", "arrows.ll"],
["\u{21C8}", "arrows.tt"],
["\u{21C9}", "arrows.rr"],
["\u{21CA}", "arrows.bb"],
["\u{21CB}", "harpoons.ltrb"],
["\u{21CC}", "harpoons.rtlb"],
["\u{21CD}", "arrow.l.double.not"],
["\u{21CE}", "arrow.l.r.double.not"],
["\u{21CF}", "arrow.r.double.not"],
["\u{21D0}", "arrow.l.double"],
["\u{21D1}", "arrow.t.double"],
["\u{21D2}", "arrow.r.double"],
["\u{21D3}", "arrow.b.double"],
["\u{21D4}", "arrow.l.r.double"],
["\u{21D5}", "arrow.t.b.double"],
["\u{21D6}", "arrow.tl.double"],
["\u{21D7}", "arrow.tr.double"],
["\u{21D8}", "arrow.br.double"],
["\u{21D9}", "arrow.bl.double"],
["\u{21DA}", "arrow.l.triple"],
["\u{21DB}", "arrow.r.triple"],
["\u{21DC}", "arrow.l.squiggly"],
["\u{21DD}", "arrow.r.squiggly"],
["\u{21DE}", "arrow.t.dstruck"],
["\u{21DF}", "arrow.b.dstruck"],
["\u{21E0}", "arrow.l.dashed"],
["\u{21E1}", "arrow.t.dashed"],
["\u{21E2}", "arrow.r.dashed"],
["\u{21E3}", "arrow.b.dashed"],
["\u{21E4}", "arrow.l.stop"],
["\u{21E5}", "arrow.r.stop"],
["\u{21E6}", "arrow.l.stroked"],
["\u{21E7}", "arrow.t.stroked"],
["\u{21E8}", "arrow.r.stroked"],
["\u{21E9}", "arrow.b.stroked"],
["\u{21F3}", "arrow.t.b.stroked"],
["\u{21F5}", "arrows.bt"],
["\u{21F6}", "arrows.rrr"],
["\u{21F7}", "arrow.l.struck"],
["\u{21F8}", "arrow.r.struck"],
["\u{21F9}", "arrow.l.r.struck"],
["\u{21FA}", "arrow.l.dstruck"],
["\u{21FB}", "arrow.r.dstruck"],
["\u{21FC}", "arrow.l.r.dstruck"],
["\u{21FD}", "arrow.l.open"],
["\u{21FE}", "arrow.r.open"],
["\u{21FF}", "arrow.l.r.open"],
["\u{2200}", "forall"],
["\u{2201}", "complement"],
["\u{2202}", "diff", "partial"],
["\u{2203}", "exists"],
["\u{2204}", "exists.not"],
["\u{2205}", "emptyset", "nothing"],
["\u{2206}", "laplace"],
["\u{2207}", "gradient", "nabla"],
["\u{2208}", "in"],
["\u{2209}", "in.not"],
["\u{220A}", "in.small"],
["\u{220B}", "in.rev"],
["\u{220C}", "in.rev.not"],
["\u{220D}", "in.rev.small"],
["\u{220E}", "qed"],
["\u{220F}", "product"],
["\u{2210}", "product.co"],
["\u{2211}", "sum"],
["\u{2212}", "minus"],
["\u{2213}", "minus.plus"],
["\u{2214}", "plus.dot"],
["\u{2216}", "without"],
["\u{2217}", "ast.op", "convolve"],
["\u{2218}", "circle.stroked.tiny", "compose"],
["\u{2219}", "bullet.op", "circle.filled.small"],
["\u{221D}", "prop"],
["\u{221E}", "infinity", "oo"],
["\u{221F}", "angle.right"],
["\u{2220}", "angle"],
["\u{2221}", "angle.arc"],
["\u{2222}", "angle.spheric"],
["\u{2223}", "divides"],
["\u{2224}", "divides.not"],
["\u{2225}", "parallel"],
["\u{2226}", "parallel.not"],
["\u{2227}", "and"],
["\u{2228}", "or"],
["\u{2229}", "inter", "sect"],
["\u{222A}", "union"],
["\u{222B}", "integral"],
["\u{222C}", "integral.double"],
["\u{222D}", "integral.triple"],
["\u{222E}", "integral.cont"],
["\u{222F}", "integral.surf"],
["\u{2230}", "integral.vol"],
["\u{2231}", "integral.cw"],
["\u{2232}", "integral.cont.cw"],
["\u{2233}", "integral.cont.ccw"],
["\u{2234}", "therefore"],
["\u{2235}", "because"],
["\u{2236}", "ratio"],
["\u{2237}", "colon.double"],
["\u{2238}", "minus.dot"],
["\u{2239}", "dash.colon"],
["\u{223C}", "tilde.op"],
["\u{223D}", "tilde.rev"],
["\u{2240}", "wreath"],
["\u{2241}", "tilde.not"],
["\u{2242}", "minus.tilde"],
["\u{2243}", "tilde.eq"],
["\u{2244}", "tilde.eq.not"],
["\u{2245}", "tilde.equiv"],
["\u{2246}", "tilde.nequiv"],
["\u{2247}", "tilde.equiv.not"],
["\u{2248}", "approx"],
["\u{2249}", "approx.not"],
["\u{224A}", "approx.eq"],
["\u{224B}", "tilde.triple"],
["\u{224C}", "tilde.rev.equiv"],
["\u{224D}", "asymp"],
["\u{2251}", "eq.dots"],
["\u{2252}", "eq.dots.down"],
["\u{2253}", "eq.dots.up"],
["\u{2254}", "colon.eq"],
["\u{2255}", "eq.colon"],
["\u{2259}", "eq.est"],
["\u{225A}", "eq.equi"],
["\u{225B}", "eq.star"],
["\u{225C}", "eq.delta"],
["\u{225D}", "eq.def"],
["\u{225E}", "eq.m"],
["\u{225F}", "eq.quest"],
["\u{2260}", "eq.not"],
["\u{2261}", "eq.triple", "equiv"],
["\u{2262}", "eq.triple.not", "equiv.not"],
["\u{2263}", "eq.quad"],
["\u{2264}", "lt.eq"],
["\u{2265}", "gt.eq"],
["\u{2266}", "lt.equiv"],
["\u{2267}", "gt.equiv"],
["\u{2268}", "lt.nequiv"],
["\u{2269}", "gt.nequiv"],
["\u{226A}", "lt.double"],
["\u{226B}", "gt.double"],
["\u{226D}", "asymp.not"],
["\u{226E}", "lt.not"],
["\u{226F}", "gt.not"],
["\u{2270}", "lt.eq.not"],
["\u{2271}", "gt.eq.not"],
["\u{2272}", "lt.tilde"],
["\u{2273}", "gt.tilde"],
["\u{2274}", "lt.tilde.not"],
["\u{2275}", "gt.tilde.not"],
["\u{2276}", "lt.gt"],
["\u{2277}", "gt.lt"],
["\u{2278}", "lt.gt.not"],
["\u{2279}", "gt.lt.not"],
["\u{227A}", "prec"],
["\u{227B}", "succ"],
["\u{227C}", "prec.curly.eq"],
["\u{227D}", "succ.curly.eq"],
["\u{227E}", "prec.tilde"],
["\u{227F}", "succ.tilde"],
["\u{2280}", "prec.not"],
["\u{2281}", "succ.not"],
["\u{2282}", "subset"],
["\u{2283}", "supset"],
["\u{2284}", "subset.not"],
["\u{2285}", "supset.not"],
["\u{2286}", "subset.eq"],
["\u{2287}", "supset.eq"],
["\u{2288}", "subset.eq.not"],
["\u{2289}", "supset.eq.not"],
["\u{228A}", "subset.neq"],
["\u{228B}", "supset.neq"],
["\u{228C}", "union.arrow"],
["\u{228D}", "union.dot"],
["\u{228E}", "union.plus"],
["\u{228F}", "subset.sq"],
["\u{2290}", "supset.sq"],
["\u{2291}", "subset.eq.sq"],
["\u{2292}", "supset.eq.sq"],
["\u{2293}", "inter.sq", "sect.sq"],
["\u{2294}", "union.sq"],
["\u{2295}", "plus.circle", "plus.o", "xor"],
["\u{2296}", "minus.circle", "minus.o"],
["\u{2297}", "times.circle", "times.o"],
["\u{2298}", "slash.o"],
["\u{2299}", "dot.circle", "dot.o"],
["\u{229A}", "circle.nested", "compose.o"],
["\u{229B}", "ast.circle", "ast.op.o", "convolve.o"],
["\u{229C}", "cc.nd", "eq.circle", "eq.o"],
["\u{229D}", "dash.circle", "dash.o"],
["\u{229E}", "plus.square"],
["\u{229F}", "minus.square"],
["\u{22A0}", "times.square"],
["\u{22A1}", "dot.square"],
["\u{22A2}", "tack.r"],
["\u{22A3}", "tack.l"],
["\u{22A4}", "tack.b", "top"],
["\u{22A5}", "bot", "tack.t"],
["\u{22A6}", "tack.r.short"],
["\u{22A7}", "models"],
["\u{22A8}", "tack.r.double"],
["\u{22A9}", "forces"],
["\u{22AC}", "tack.r.not"],
["\u{22AD}", "tack.r.double.not"],
["\u{22AE}", "forces.not"],
["\u{22B2}", "lt.tri"],
["\u{22B3}", "gt.tri"],
["\u{22B4}", "lt.tri.eq"],
["\u{22B5}", "gt.tri.eq"],
["\u{22B6}", "original"],
["\u{22B7}", "image"],
["\u{22B8}", "multimap"],
["\u{22BE}", "angle.right.arc"],
["\u{22C0}", "and.big"],
["\u{22C1}", "or.big"],
["\u{22C2}", "inter.big", "sect.big"],
["\u{22C3}", "union.big"],
["\u{22C4}", "diamond.stroked.small"],
["\u{22C5}", "dot.op"],
["\u{22C6}", "star.op"],
["\u{22C7}", "times.div"],
["\u{22C9}", "times.l"],
["\u{22CA}", "times.r"],
["\u{22CB}", "times.three.l"],
["\u{22CC}", "times.three.r"],
["\u{22CD}", "tilde.eq.rev"],
["\u{22CE}", "or.curly"],
["\u{22CF}", "and.curly"],
["\u{22D0}", "subset.double"],
["\u{22D1}", "supset.double"],
["\u{22D2}", "inter.double", "sect.double"],
["\u{22D3}", "union.double"],
["\u{22D5}", "parallel.eq"],
["\u{22D6}", "lt.dot"],
["\u{22D7}", "gt.dot"],
["\u{22D8}", "lt.triple"],
["\u{22D9}", "gt.triple"],
["\u{22DA}", "lt.eq.gt"],
["\u{22DB}", "gt.eq.lt"],
["\u{22DC}", "eq.lt"],
["\u{22DD}", "eq.gt"],
["\u{22DE}", "eq.prec"],
["\u{22DF}", "eq.succ"],
["\u{22E0}", "prec.curly.eq.not"],
["\u{22E1}", "succ.curly.eq.not"],
["\u{22E2}", "subset.eq.sq.not"],
["\u{22E3}", "supset.eq.sq.not"],
["\u{22E4}", "subset.sq.neq"],
["\u{22E5}", "supset.sq.neq"],
["\u{22E6}", "lt.ntilde"],
["\u{22E7}", "gt.ntilde"],
["\u{22E8}", "prec.ntilde"],
["\u{22E9}", "succ.ntilde"],
["\u{22EA}", "lt.tri.not"],
["\u{22EB}", "gt.tri.not"],
["\u{22EC}", "lt.tri.eq.not"],
["\u{22ED}", "gt.tri.eq.not"],
["\u{22EE}", "dots.v"],
["\u{22EF}", "dots.h.c"],
["\u{22F0}", "dots.up"],
["\u{22F1}", "dots.down"],
["\u{2300}", "diameter"],
["\u{2303}", "arrowhead.t"],
["\u{2304}", "arrowhead.b"],
["\u{2308}", "ceil.l"],
["\u{2309}", "ceil.r"],
["\u{230A}", "floor.l"],
["\u{230B}", "floor.r"],
["\u{231C}", "corner.l.t"],
["\u{231D}", "corner.r.t"],
["\u{231E}", "corner.l.b"],
["\u{231F}", "corner.r.b"],
["\u{2322}", "frown"],
["\u{2323}", "smile"],
["\u{237C}", "angle.azimuth", "angzarr"],
["\u{23B0}", "mustache.l"],
["\u{23B1}", "mustache.r"],
["\u{23B4}", "bracket.t"],
["\u{23B5}", "bracket.b"],
["\u{23DC}", "paren.t"],
["\u{23DD}", "paren.b"],
["\u{23DE}", "brace.t"],
["\u{23DF}", "brace.b"],
["\u{23E0}", "shell.t"],
["\u{23E1}", "shell.b"],
["\u{23FB}", "power.standby"],
["\u{23FC}", "power.on.off"],
["\u{23FD}", "power.on"],
["\u{23FE}", "power.sleep"],
["\u{25A0}", "square.filled"],
["\u{25A1}", "square.stroked"],
["\u{25A2}", "square.stroked.rounded"],
["\u{25AA}\u{FE0E}", "square.filled.tiny"],
["\u{25AB}\u{FE0E}", "square.stroked.tiny"],
["\u{25AC}", "rect.filled.h"],
["\u{25AD}", "rect.stroked.h"],
["\u{25AE}", "rect.filled.v"],
["\u{25AF}", "rect.stroked.v"],
["\u{25B0}", "parallelogram.filled"],
["\u{25B1}", "parallelogram.stroked"],
["\u{25B2}", "triangle.filled.t"],
["\u{25B3}", "triangle.stroked.t"],
["\u{25B4}", "triangle.filled.small.t"],
["\u{25B5}", "triangle.stroked.small.t"],
["\u{25B6}\u{FE0E}", "triangle.filled.r"],
["\u{25B7}", "triangle.stroked.r"],
["\u{25B8}", "triangle.filled.small.r"],
["\u{25B9}", "triangle.stroked.small.r"],
["\u{25BC}", "triangle.filled.b"],
["\u{25BD}", "triangle.stroked.b"],
["\u{25BE}", "triangle.filled.small.b"],
["\u{25BF}", "triangle.stroked.small.b"],
["\u{25C0}\u{FE0E}", "triangle.filled.l"],
["\u{25C1}", "triangle.stroked.l"],
["\u{25C2}", "triangle.filled.small.l"],
["\u{25C3}", "triangle.stroked.small.l"],
["\u{25C6}", "diamond.filled"],
["\u{25C7}", "diamond.stroked"],
["\u{25CA}", "lozenge.stroked"],
["\u{25CB}", "circle.stroked"],
["\u{25CC}", "circle.dotted"],
["\u{25CF}", "circle.filled"],
["\u{25D8}", "bullet.hole"],
["\u{25E2}", "triangle.filled.br"],
["\u{25E3}", "triangle.filled.bl"],
["\u{25E4}", "triangle.filled.tl"],
["\u{25E5}", "triangle.filled.tr"],
["\u{25E6}", "bullet.stroked"],
["\u{25EC}", "triangle.stroked.dot"],
["\u{25EF}", "circle.stroked.big"],
["\u{25F8}", "triangle.stroked.tl"],
["\u{25F9}", "triangle.stroked.tr"],
["\u{25FA}", "triangle.stroked.bl"],
["\u{25FB}\u{FE0E}", "square.stroked.medium"],
["\u{25FC}\u{FE0E}", "square.filled.medium"],
["\u{25FD}\u{FE0E}", "square.stroked.small"],
["\u{25FE}\u{FE0E}", "square.filled.small"],
["\u{25FF}", "triangle.stroked.br"],
["\u{2605}", "star.filled"],
["\u{2606}", "star.stroked"],
["\u{2609}", "sun"],
["\u{2610}", "ballot"],
["\u{2611}\u{FE0E}", "ballot.check"],
["\u{2612}", "ballot.cross"],
["\u{2619}", "floral.l"],
["\u{263F}", "mercury"],
["\u{2640}\u{FE0E}", "gender.female", "venus"],
["\u{2641}", "earth.alt"],
["\u{2642}\u{FE0E}", "gender.male", "mars"],
["\u{2643}", "jupiter"],
["\u{2644}", "saturn"],
["\u{2645}", "uranus.alt"],
["\u{2646}", "neptune"],
["\u{2660}\u{FE0E}", "suit.spade.filled"],
["\u{2661}", "suit.heart.stroked"],
["\u{2662}", "suit.diamond.stroked"],
["\u{2663}\u{FE0E}", "suit.club.filled"],
["\u{2664}", "suit.spade.stroked"],
["\u{2665}\u{FE0E}", "suit.heart.filled"],
["\u{2666}\u{FE0E}", "suit.diamond.filled"],
["\u{2667}", "suit.club.stroked"],
["\u{2669}", "note.quarter.alt"],
["\u{266A}", "note.eighth.alt"],
["\u{266B}", "note.eighth.beamed"],
["\u{266C}", "note.sixteenth.beamed"],
["\u{266D}", "flat"],
["\u{266E}", "natural"],
["\u{266F}", "sharp"],
["\u{2680}", "die.one"],
["\u{2681}", "die.two"],
["\u{2682}", "die.three"],
["\u{2683}", "die.four"],
["\u{2684}", "die.five"],
["\u{2685}", "die.six"],
["\u{26A2}", "gender.female.double"],
["\u{26A3}", "gender.male.double"],
["\u{26A4}", "gender.female.male", "gender.male.female"],
["\u{26A5}", "gender.intersex"],
["\u{26A6}", "gender.male.stroke"],
["\u{26A7}\u{FE0E}", "gender.trans"],
["\u{26A8}", "gender.male.stroke.t"],
["\u{26A9}", "gender.male.stroke.r"],
["\u{26AC}", "circle.stroked.small"],
["\u{26B2}", "gender.neuter"],
["\u{26E2}", "uranus"],
["\u{2713}", "checkmark"],
["\u{2714}\u{FE0E}", "checkmark.heavy"],
["\u{2717}", "crossmark"],
["\u{2718}", "crossmark.heavy"],
["\u{2720}", "maltese"],
["\u{2766}", "floral"],
["\u{2767}", "floral.r"],
["\u{2772}", "shell.l"],
["\u{2773}", "shell.r"],
["\u{27A1}\u{FE0E}", "arrow.r.filled"],
["\u{27C0}", "angle.spatial"],
["\u{27C1}", "triangle.stroked.nested"],
["\u{27C2}", "perp"],
["\u{27C5}", "bag.l"],
["\u{27C6}", "bag.r"],
["\u{27C7}", "or.dot"],
["\u{27CA}", "divides.struck"],
["\u{27D0}", "diamond.stroked.dot"],
["\u{27D1}", "and.dot"],
["\u{27D5}", "join.l"],
["\u{27D6}", "join.r"],
["\u{27D7}", "join.l.r"],
["\u{27D8}", "tack.t.big"],
["\u{27D9}", "tack.b.big"],
["\u{27DB}", "tack.l.r"],
["\u{27DD}", "tack.r.long"],
["\u{27DE}", "tack.l.long"],
["\u{27E6}", "bracket.l.double", "bracket.l.stroked"],
["\u{27E7}", "bracket.r.double", "bracket.r.stroked"],
["\u{27E8}", "angle.l", "chevron.l"],
["\u{27E9}", "angle.r", "chevron.r"],
["\u{27EA}", "angle.l.double", "chevron.l.double"],
["\u{27EB}", "angle.r.double", "chevron.r.double"],
["\u{27EC}", "shell.l.double", "shell.l.stroked"],
["\u{27ED}", "shell.r.double", "shell.r.stroked"],
["\u{27EE}", "paren.l.flat"],
["\u{27EF}", "paren.r.flat"],
["\u{27F0}", "arrow.t.quad"],
["\u{27F1}", "arrow.b.quad"],
["\u{27F4}", "plus.circle.arrow", "plus.o.arrow"],
["\u{27F5}", "arrow.l.long"],
["\u{27F6}", "arrow.r.long"],
["\u{27F7}", "arrow.l.r.long"],
["\u{27F8}", "arrow.l.double.long"],
["\u{27F9}", "arrow.r.double.long"],
["\u{27FA}", "arrow.l.r.double.long"],
["\u{27FB}", "arrow.l.long.bar"],
["\u{27FC}", "arrow.r.long.bar", "mapsto.long"],
["\u{27FD}", "arrow.l.double.long.bar"],
["\u{27FE}", "arrow.r.double.long.bar"],
["\u{27FF}", "arrow.r.long.squiggly"],
["\u{2900}", "arrow.r.twohead.struck"],
["\u{2901}", "arrow.r.twohead.dstruck"],
["\u{2902}", "arrow.l.double.struck"],
["\u{2903}", "arrow.r.double.struck"],
["\u{2904}", "arrow.l.r.double.struck"],
["\u{2905}", "arrow.r.twohead.bar"],
["\u{2906}", "arrow.l.double.bar"],
["\u{2907}", "arrow.r.double.bar"],
["\u{2908}", "arrow.b.struck"],
["\u{2909}", "arrow.t.struck"],
["\u{290A}", "arrow.t.triple"],
["\u{290B}", "arrow.b.triple"],
["\u{2911}", "arrow.r.dotted"],
["\u{2912}", "arrow.t.stop"],
["\u{2913}", "arrow.b.stop"],
["\u{2914}", "arrow.r.tail.struck"],
["\u{2915}", "arrow.r.tail.dstruck"],
["\u{2916}", "arrow.r.twohead.tail"],
["\u{2917}", "arrow.r.twohead.tail.struck"],
["\u{2918}", "arrow.r.twohead.tail.dstruck"],
["\u{2921}", "arrow.tl.br"],
["\u{2922}", "arrow.tr.bl"],
["\u{2923}", "arrow.tl.hook"],
["\u{2924}", "arrow.tr.hook"],
["\u{2925}", "arrow.br.hook"],
["\u{2926}", "arrow.bl.hook"],
["\u{2934}\u{FE0E}", "arrow.t.curve"],
["\u{2935}\u{FE0E}", "arrow.b.curve"],
["\u{2936}", "arrow.l.curve"],
["\u{2937}", "arrow.r.curve"],
["\u{294A}", "harpoon.lt.rb"],
["\u{294B}", "harpoon.lb.rt"],
["\u{294C}", "harpoon.tr.bl"],
["\u{294D}", "harpoon.tl.br"],
["\u{294E}", "harpoon.lt.rt"],
["\u{294F}", "harpoon.tr.br"],
["\u{2950}", "harpoon.lb.rb"],
["\u{2951}", "harpoon.tl.bl"],
["\u{2952}", "harpoon.lt.stop"],
["\u{2953}", "harpoon.rt.stop"],
["\u{2954}", "harpoon.tr.stop"],
["\u{2955}", "harpoon.br.stop"],
["\u{2956}", "harpoon.lb.stop"],
["\u{2957}", "harpoon.rb.stop"],
["\u{2958}", "harpoon.tl.stop"],
["\u{2959}", "harpoon.bl.stop"],
["\u{295A}", "harpoon.lt.bar"],
["\u{295B}", "harpoon.rt.bar"],
["\u{295C}", "harpoon.tr.bar"],
["\u{295D}", "harpoon.br.bar"],
["\u{295E}", "harpoon.lb.bar"],
["\u{295F}", "harpoon.rb.bar"],
["\u{2960}", "harpoon.tl.bar"],
["\u{2961}", "harpoon.bl.bar"],
["\u{2962}", "harpoons.ltlb"],
["\u{2963}", "harpoons.tltr"],
["\u{2964}", "harpoons.rtrb"],
["\u{2965}", "harpoons.blbr"],
["\u{2966}", "harpoons.ltrt"],
["\u{2967}", "harpoons.lbrb"],
["\u{2968}", "harpoons.rtlt"],
["\u{2969}", "harpoons.rblb"],
["\u{296E}", "harpoons.tlbr"],
["\u{296F}", "harpoons.bltr"],
["\u{2972}", "arrow.r.tilde"],
["\u{2980}", "bar.v.triple"],
["\u{2981}", "circle.filled.tiny"],
["\u{2983}", "brace.l.double", "brace.l.stroked"],
["\u{2984}", "brace.r.double", "brace.r.stroked"],
["\u{2985}", "paren.l.double", "paren.l.stroked"],
["\u{2986}", "paren.r.double", "paren.r.stroked"],
["\u{2987}", "paren.l.closed"],
["\u{2988}", "paren.r.closed"],
["\u{2989}", "chevron.l.closed"],
["\u{298A}", "chevron.r.closed"],
["\u{298D}", "bracket.l.tick.t"],
["\u{298E}", "bracket.r.tick.b"],
["\u{298F}", "bracket.l.tick.b"],
["\u{2990}", "bracket.r.tick.t"],
["\u{2991}", "angle.l.dot", "chevron.l.dot"],
["\u{2992}", "angle.r.dot", "chevron.r.dot"],
["\u{2997}", "shell.l.filled"],
["\u{2998}", "shell.r.filled"],
["\u{2999}", "fence.dotted"],
["\u{299B}", "angle.arc.rev"],
["\u{299C}", "angle.right.sq"],
["\u{299D}", "angle.right.dot"],
["\u{299E}", "angle.s"],
["\u{299F}", "angle.acute"],
["\u{29A0}", "angle.spheric.rev"],
["\u{29A1}", "angle.spheric.t", "angle.spheric.top"],
["\u{29A3}", "angle.rev"],
["\u{29A6}", "angle.oblique", "angle.obtuse"],
["\u{29B0}", "emptyset.rev", "nothing.rev"],
["\u{29B1}", "emptyset.bar", "nothing.bar"],
["\u{29B2}", "emptyset.circle", "nothing.circle"],
["\u{29B3}", "emptyset.arrow.r", "nothing.arrow.r"],
["\u{29B4}", "emptyset.arrow.l", "nothing.arrow.l"],
["\u{29B6}", "bar.v.circle", "bar.v.o"],
["\u{29B7}", "parallel.circle", "parallel.o"],
["\u{29B8}", "backslash.circle", "backslash.o"],
["\u{29B9}", "perp.circle", "perp.o"],
["\u{29BC}", "div.slanted.o"],
["\u{29BE}", "bullet.stroked.o"],
["\u{29BF}", "bullet.o"],
["\u{29C0}", "lt.circle", "lt.o"],
["\u{29C1}", "gt.circle", "gt.o"],
["\u{29C6}", "ast.square"],
["\u{29D6}", "hourglass.stroked"],
["\u{29D7}", "hourglass.filled"],
["\u{29D8}", "fence.l"],
["\u{29D9}", "fence.r"],
["\u{29DA}", "fence.l.double"],
["\u{29DB}", "fence.r.double"],
["\u{29DC}", "infinity.incomplete"],
["\u{29DD}", "infinity.tie"],
["\u{29DE}", "infinity.bar"],
["\u{29DF}", "multimap.double"],
["\u{29E3}", "parallel.slanted.eq"],
["\u{29E4}", "parallel.slanted.eq.tilde"],
["\u{29E5}", "parallel.slanted.equiv"],
["\u{29EB}", "lozenge.filled"],
["\u{29EE}", "errorbar.square.stroked"],
["\u{29EF}", "errorbar.square.filled"],
["\u{29F0}", "errorbar.diamond.stroked"],
["\u{29F1}", "errorbar.diamond.filled"],
["\u{29F2}", "errorbar.circle.stroked"],
["\u{29F3}", "errorbar.circle.filled"],
["\u{29F7}", "backslash.not"],
["\u{29F8}", "slash.big"],
["\u{29FA}", "plus.double"],
["\u{29FB}", "plus.triple"],
["\u{29FC}", "angle.l.curly", "chevron.l.curly"],
["\u{29FD}", "angle.r.curly", "chevron.r.curly"],
["\u{29FE}", "tiny"],
["\u{29FF}", "miny"],
["\u{2A00}", "dot.circle.big", "dot.o.big"],
["\u{2A01}", "plus.circle.big", "plus.o.big", "xor.big"],
["\u{2A02}", "times.circle.big", "times.o.big"],
["\u{2A03}", "union.dot.big"],
["\u{2A04}", "union.plus.big"],
["\u{2A05}", "inter.sq.big", "sect.sq.big"],
["\u{2A06}", "union.sq.big"],
["\u{2A09}", "times.big"],
["\u{2A0B}", "sum.integral"],
["\u{2A0C}", "integral.quad"],
["\u{2A0D}", "integral.dash"],
["\u{2A0E}", "integral.dash.double"],
["\u{2A0F}", "integral.slash"],
["\u{2A11}", "integral.ccw"],
["\u{2A16}", "integral.square"],
["\u{2A17}", "integral.arrow.hook"],
["\u{2A18}", "integral.times"],
["\u{2A19}", "integral.inter", "integral.sect"],
["\u{2A1A}", "integral.union"],
["\u{2A1D}", "join"],
["\u{2A2D}", "plus.o.l"],
["\u{2A2E}", "plus.o.r"],
["\u{2A33}", "smash"],
["\u{2A34}", "times.o.l"],
["\u{2A35}", "times.o.r"],
["\u{2A36}", "times.o.hat"],
["\u{2A38}", "div.circle", "div.o"],
["\u{2A39}", "plus.triangle"],
["\u{2A3A}", "minus.triangle"],
["\u{2A3B}", "times.triangle"],
["\u{2A40}", "inter.dot", "sect.dot"],
["\u{2A41}", "union.minus"],
["\u{2A44}", "inter.and", "sect.and"],
["\u{2A45}", "union.or"],
["\u{2A4E}", "inter.sq.double", "sect.sq.double"],
["\u{2A4F}", "union.sq.double"],
["\u{2A53}", "and.double"],
["\u{2A54}", "or.double"],
["\u{2A68}", "parallel.equiv"],
["\u{2A6A}", "tilde.dot"],
["\u{2A74}", "colon.double.eq"],
["\u{2A7D}", "lt.eq.slant"],
["\u{2A7E}", "gt.eq.slant"],
["\u{2A85}", "lt.approx"],
["\u{2A86}", "gt.approx"],
["\u{2A87}", "lt.neq"],
["\u{2A88}", "gt.neq"],
["\u{2A89}", "lt.napprox"],
["\u{2A8A}", "gt.napprox"],
["\u{2AAA}", "smt"],
["\u{2AAB}", "lat"],
["\u{2AAC}", "smt.eq"],
["\u{2AAD}", "lat.eq"],
["\u{2AAF}", "prec.eq"],
["\u{2AB0}", "succ.eq"],
["\u{2AB1}", "prec.neq"],
["\u{2AB2}", "succ.neq"],
["\u{2AB3}", "prec.equiv"],
["\u{2AB4}", "succ.equiv"],
["\u{2AB5}", "prec.nequiv"],
["\u{2AB6}", "succ.nequiv"],
["\u{2AB7}", "prec.approx"],
["\u{2AB8}", "succ.approx"],
["\u{2AB9}", "prec.napprox"],
["\u{2ABA}", "succ.napprox"],
["\u{2ABB}", "prec.double"],
["\u{2ABC}", "succ.double"],
["\u{2ABD}", "subset.dot"],
["\u{2ABE}", "supset.dot"],
["\u{2ADE}", "tack.l.short"],
["\u{2ADF}", "tack.b.short"],
["\u{2AE0}", "tack.t.short"],
["\u{2AE4}", "tack.l.double"],
["\u{2AEA}", "tack.b.double"],
["\u{2AEB}", "tack.t.double"],
["\u{2AEE}", "divides.not.rev"],
["\u{2AF2}", "parallel.struck"],
["\u{2AF3}", "parallel.tilde"],
["\u{2AF4}", "interleave"],
["\u{2AF5}", "interleave.struck"],
["\u{2AF6}", "colon.tri.op"],
["\u{2AF7}", "lt.triple.nested"],
["\u{2AF8}", "gt.triple.nested"],
["\u{2AFB}", "slash.triple"],
["\u{2AFC}", "interleave.big"],
["\u{2AFD}", "slash.double"],
["\u{2B00}", "arrow.tr.stroked"],
["\u{2B01}", "arrow.tl.stroked"],
["\u{2B02}", "arrow.br.stroked"],
["\u{2B03}", "arrow.bl.stroked"],
["\u{2B04}", "arrow.l.r.stroked"],
["\u{2B05}\u{FE0E}", "arrow.l.filled"],
["\u{2B06}\u{FE0E}", "arrow.t.filled"],
["\u{2B07}\u{FE0E}", "arrow.b.filled"],
["\u{2B08}", "arrow.tr.filled"],
["\u{2B09}", "arrow.tl.filled"],
["\u{2B0A}", "arrow.br.filled"],
["\u{2B0B}", "arrow.bl.filled"],
["\u{2B0C}", "arrow.l.r.filled"],
["\u{2B0D}", "arrow.t.b.filled"],
["\u{2B1A}", "square.stroked.dotted"],
["\u{2B1B}\u{FE0E}", "square.filled.big"],
["\u{2B1C}\u{FE0E}", "square.stroked.big"],
["\u{2B1F}", "penta.filled"],
["\u{2B20}", "penta.stroked"],
["\u{2B21}", "hexa.stroked"],
["\u{2B22}", "hexa.filled"],
["\u{2B24}", "circle.filled.big"],
["\u{2B25}", "diamond.filled.medium"],
["\u{2B26}", "diamond.stroked.medium"],
["\u{2B27}", "lozenge.filled.medium"],
["\u{2B28}", "lozenge.stroked.medium"],
["\u{2B29}", "diamond.filled.small"],
["\u{2B2A}", "lozenge.filled.small"],
["\u{2B2B}", "lozenge.stroked.small"],
["\u{2B2C}", "ellipse.filled.h"],
["\u{2B2D}", "ellipse.stroked.h"],
["\u{2B2E}", "ellipse.filled.v"],
["\u{2B2F}", "ellipse.stroked.v"],
["\u{2B31}", "arrows.lll"],
["\u{2B33}", "arrow.l.long.squiggly"],
["\u{2B34}", "arrow.l.twohead.struck"],
["\u{2B35}", "arrow.l.twohead.dstruck"],
["\u{2B36}", "arrow.l.twohead.bar"],
["\u{2B38}", "arrow.l.dotted"],
["\u{2B39}", "arrow.l.tail.struck"],
["\u{2B3A}", "arrow.l.tail.dstruck"],
["\u{2B3B}", "arrow.l.twohead.tail"],
["\u{2B3C}", "arrow.l.twohead.tail.struck"],
["\u{2B3D}", "arrow.l.twohead.tail.dstruck"],
["\u{2B45}", "arrow.l.quad"],
["\u{2B46}", "arrow.r.quad"],
["\u{2B49}", "arrow.l.tilde"],
["\u{2B58}", "power.off"],
["\u{2B8C}", "arrow.l.turn"],
["\u{2B8D}", "arrow.t.turn"],
["\u{2B8E}", "arrow.r.turn"],
["\u{2B8F}", "arrow.b.turn"],
["\u{2BC9}", "neptune.alt"],
["\u{2BFE}", "angle.right.rev"],
["\u{2E18}", "interrobang.inv"],
["\u{2E32}", "comma.inv"],
["\u{2E35}", "semi.inv"],
["\u{2E36}", "dagger.l"],
["\u{2E37}", "dagger.r"],
["\u{2E38}", "dagger.inv"],
["\u{2E3A}", "dash.em.two"],
["\u{2E3B}", "dash.em.three"],
["\u{2E41}", "comma.rev"],
["\u{2E4B}", "dagger.triple"],
["\u{301C}", "dash.wave"],
["\u{3030}\u{FE0E}", "dash.wave.double"],
["\u{1D129}", "rest.multiple.measure"],
["\u{1D12A}", "sharp.double"],
["\u{1D12B}", "flat.double"],
["\u{1D12C}", "flat.t"],
["\u{1D12D}", "flat.b"],
["\u{1D12E}", "natural.t"],
["\u{1D12F}", "natural.b"],
["\u{1D130}", "sharp.t"],
["\u{1D131}", "sharp.b"],
["\u{1D132}", "sharp.quarter"],
["\u{1D133}", "flat.quarter"],
["\u{1D13A}", "rest.multiple"],
["\u{1D13B}", "rest.whole"],
["\u{1D13C}", "rest.half"],
["\u{1D13D}", "rest.quarter"],
["\u{1D13E}", "rest.eighth"],
["\u{1D13F}", "rest.sixteenth"],
["\u{1D15D}", "note.whole"],
["\u{1D15E}", "note.half"],
["\u{1D15F}", "note.quarter"],
["\u{1D160}", "note.eighth"],
["\u{1D161}", "note.sixteenth"],
["\u{1D194}", "note.grace.slash"],
["\u{1D195}", "note.grace"],
["\u{1D538}", "AA"],
["\u{1D539}", "BB"],
["\u{1D53B}", "DD"],
["\u{1D53C}", "EE"],
["\u{1D53D}", "FF"],
["\u{1D53E}", "GG"],
["\u{1D540}", "II"],
["\u{1D541}", "JJ"],
["\u{1D542}", "KK"],
["\u{1D543}", "LL"],
["\u{1D544}", "MM"],
["\u{1D546}", "OO"],
["\u{1D54A}", "SS"],
["\u{1D54B}", "TT"],
["\u{1D54C}", "UU"],
["\u{1D54D}", "VV"],
["\u{1D54E}", "WW"],
["\u{1D54F}", "XX"],
["\u{1D550}", "YY"],
["\u{1E2FF}", "rupee.wancho"],
["\u{1F10D}", "cc.zero"],
["\u{1F10E}", "cc.sa"],
["\u{1F10F}", "cc.nc"],
["\u{1F12F}", "copyleft"],
["\u{1F16D}", "cc"],
["\u{1F16E}", "cc.public"],
["\u{1F16F}", "cc.by"],
["\u{1F39C}", "note.up"],
["\u{1F39D}", "note.down"],
["\u{1F5F8}", "checkmark.light"],
["\u{1F5F9}", "ballot.check.heavy"],
["\u{1F6C6}", "triangle.stroked.rounded"],
["\u{1F728}", "earth"],
["\u{FE61}", "ast.small"],
["\u{FE62}", "plus.small"],
["\u{FE64}", "lt.small"],
["\u{FE65}", "gt.small"],
["\u{FE66}", "eq.small"]
];

const map_grapheme_to_notations = new Map(
  notation_table.map((record) => [record[0], record.slice(1)]),
);

const map_notation_to_grapheme = new Map(
  notation_table.flatMap((record) =>
    record.slice(1).map((notation) => [notation, record[0]])
  ),
);
