// Generated from https://www.unicode.org/Public/UCD/latest/ucd/PropertyValueAliases.txt

import { Error, Ok, toList } from "../../gleam.mjs";
import { comparable_property } from "../internal.mjs";

export function get_list() {
  return list;
}

export function short_name_to_long_name(short) {
  let long = map_short_to_long.get(short);
  if (long === undefined) {
    return new Error(undefined);
  } else {
    return new Ok(long);
  }
}

export function long_name_to_short_name(long) {
  let short = map_long_to_short.get(long);
  if (short === undefined) {
    return new Error(undefined);
  } else {
    return new Ok(short);
  }
}

const scripts = [
["adlm", "Adlam"],
["aghb", "Caucasian_Albanian"],
["ahom", "Ahom"],
["arab", "Arabic"],
["armi", "Imperial_Aramaic"],
["armn", "Armenian"],
["avst", "Avestan"],
["bali", "Balinese"],
["bamu", "Bamum"],
["bass", "Bassa_Vah"],
["batk", "Batak"],
["beng", "Bengali"],
["bhks", "Bhaiksuki"],
["bopo", "Bopomofo"],
["brah", "Brahmi"],
["brai", "Braille"],
["bugi", "Buginese"],
["buhd", "Buhid"],
["cakm", "Chakma"],
["cans", "Canadian_Aboriginal"],
["cari", "Carian"],
["cham", "Cham"],
["cher", "Cherokee"],
["chrs", "Chorasmian"],
["copt", "Coptic"],
["cpmn", "Cypro_Minoan"],
["cprt", "Cypriot"],
["cyrl", "Cyrillic"],
["deva", "Devanagari"],
["diak", "Dives_Akuru"],
["dogr", "Dogra"],
["dsrt", "Deseret"],
["dupl", "Duployan"],
["egyp", "Egyptian_Hieroglyphs"],
["elba", "Elbasan"],
["elym", "Elymaic"],
["ethi", "Ethiopic"],
["gara", "Garay"],
["geor", "Georgian"],
["glag", "Glagolitic"],
["gong", "Gunjala_Gondi"],
["gonm", "Masaram_Gondi"],
["goth", "Gothic"],
["gran", "Grantha"],
["grek", "Greek"],
["gujr", "Gujarati"],
["gukh", "Gurung_Khema"],
["guru", "Gurmukhi"],
["hang", "Hangul"],
["hani", "Han"],
["hano", "Hanunoo"],
["hatr", "Hatran"],
["hebr", "Hebrew"],
["hira", "Hiragana"],
["hluw", "Anatolian_Hieroglyphs"],
["hmng", "Pahawh_Hmong"],
["hmnp", "Nyiakeng_Puachue_Hmong"],
["hrkt", "Katakana_Or_Hiragana"],
["hung", "Old_Hungarian"],
["ital", "Old_Italic"],
["java", "Javanese"],
["kali", "Kayah_Li"],
["kana", "Katakana"],
["kawi", "Kawi"],
["khar", "Kharoshthi"],
["khmr", "Khmer"],
["khoj", "Khojki"],
["kits", "Khitan_Small_Script"],
["knda", "Kannada"],
["krai", "Kirat_Rai"],
["kthi", "Kaithi"],
["lana", "Tai_Tham"],
["laoo", "Lao"],
["latn", "Latin"],
["lepc", "Lepcha"],
["limb", "Limbu"],
["lina", "Linear_A"],
["linb", "Linear_B"],
["lisu", "Lisu"],
["lyci", "Lycian"],
["lydi", "Lydian"],
["mahj", "Mahajani"],
["maka", "Makasar"],
["mand", "Mandaic"],
["mani", "Manichaean"],
["marc", "Marchen"],
["medf", "Medefaidrin"],
["mend", "Mende_Kikakui"],
["merc", "Meroitic_Cursive"],
["mero", "Meroitic_Hieroglyphs"],
["mlym", "Malayalam"],
["modi", "Modi"],
["mong", "Mongolian"],
["mroo", "Mro"],
["mtei", "Meetei_Mayek"],
["mult", "Multani"],
["mymr", "Myanmar"],
["nagm", "Nag_Mundari"],
["nand", "Nandinagari"],
["narb", "Old_North_Arabian"],
["nbat", "Nabataean"],
["newa", "Newa"],
["nkoo", "Nko"],
["nshu", "Nushu"],
["ogam", "Ogham"],
["olck", "Ol_Chiki"],
["onao", "Ol_Onal"],
["orkh", "Old_Turkic"],
["orya", "Oriya"],
["osge", "Osage"],
["osma", "Osmanya"],
["ougr", "Old_Uyghur"],
["palm", "Palmyrene"],
["pauc", "Pau_Cin_Hau"],
["perm", "Old_Permic"],
["phag", "Phags_Pa"],
["phli", "Inscriptional_Pahlavi"],
["phlp", "Psalter_Pahlavi"],
["phnx", "Phoenician"],
["plrd", "Miao"],
["prti", "Inscriptional_Parthian"],
["rjng", "Rejang"],
["rohg", "Hanifi_Rohingya"],
["runr", "Runic"],
["samr", "Samaritan"],
["sarb", "Old_South_Arabian"],
["saur", "Saurashtra"],
["sgnw", "SignWriting"],
["shaw", "Shavian"],
["shrd", "Sharada"],
["sidd", "Siddham"],
["sind", "Khudawadi"],
["sinh", "Sinhala"],
["sogd", "Sogdian"],
["sogo", "Old_Sogdian"],
["sora", "Sora_Sompeng"],
["soyo", "Soyombo"],
["sund", "Sundanese"],
["sunu", "Sunuwar"],
["sylo", "Syloti_Nagri"],
["syrc", "Syriac"],
["tagb", "Tagbanwa"],
["takr", "Takri"],
["tale", "Tai_Le"],
["talu", "New_Tai_Lue"],
["taml", "Tamil"],
["tang", "Tangut"],
["tavt", "Tai_Viet"],
["telu", "Telugu"],
["tfng", "Tifinagh"],
["tglg", "Tagalog"],
["thaa", "Thaana"],
["thai", "Thai"],
["tibt", "Tibetan"],
["tirh", "Tirhuta"],
["tnsa", "Tangsa"],
["todr", "Todhri"],
["toto", "Toto"],
["tutg", "Tulu_Tigalari"],
["ugar", "Ugaritic"],
["vaii", "Vai"],
["vith", "Vithkuqi"],
["wara", "Warang_Citi"],
["wcho", "Wancho"],
["xpeo", "Old_Persian"],
["xsux", "Cuneiform"],
["yezi", "Yezidi"],
["yiii", "Yi"],
["zanb", "Zanabazar_Square"],
["zinh", "Inherited"],
["zyyy", "Common"],
["zzzz", "Unknown"]
];

const list = /* @__PURE__ */ toList(scripts.map((record) => record[0]));

const map_short_to_long = /* @__PURE__ */ new Map(
  scripts.map((record) => [record[0], record[1]]),
);

const map_long_to_short = /* @__PURE__ */ new Map(
  scripts.map((record) => [comparable_property(record[1]), record[0]]),
);
