name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Erlang & Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          rebar3-version: "3"
          gleam-version: "1.12.0"
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build application
        working-directory: app
        run: |
            gleam build
            gleam run -m lustre/dev add bun
            gleam run -m lustre/dev build --minify
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'app/dist'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
